### ISSUE TITLE
not working propertly in the last version of elementary

### ISSUE THREAD

**Issue by bakeiro** [yarik-vv/OS-X-buttons#1]
The layout dont fit correctly and the animations of the icons doesnt work in the last version

**Comment by yarik-vv** [comment]
@bakeiro wow, sorry, I didn’t even think that this was interesting to someone :>
Is this issue relevant to you?

**Comment by bakeiro** [comment]
hmm yes? ahah, I mean, I can live without this theme, but better it works xd
